# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/activation_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacemesh.v1 import types_pb2 as spacemesh_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#spacemesh/v1/activation_types.proto\x12\x0cspacemesh.v1\x1a\x18spacemesh/v1/types.proto\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x0c\"o\n\x0bGetResponse\x12%\n\x03\x61tx\x18\x01 \x01(\x0b\x32\x18.spacemesh.v1.Activation\x12\x39\n\x11malfeasance_proof\x18\x02 \x01(\x0b\x32\x1e.spacemesh.v1.MalfeasanceProof\"8\n\x0fHighestResponse\x12%\n\x03\x61tx\x18\x01 \x01(\x0b\x32\x18.spacemesh.v1.ActivationB4Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.activation_types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_GETREQUEST']._serialized_start=79
  _globals['_GETREQUEST']._serialized_end=103
  _globals['_GETRESPONSE']._serialized_start=105
  _globals['_GETRESPONSE']._serialized_end=216
  _globals['_HIGHESTRESPONSE']._serialized_start=218
  _globals['_HIGHESTRESPONSE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
