# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/activation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacemesh.v1 import activation_types_pb2 as spacemesh_dot_v1_dot_activation__types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dspacemesh/v1/activation.proto\x12\x0cspacemesh.v1\x1a#spacemesh/v1/activation_types.proto\x1a\x1bgoogle/protobuf/empty.proto2\x91\x01\n\x11\x41\x63tivationService\x12:\n\x03Get\x12\x18.spacemesh.v1.GetRequest\x1a\x19.spacemesh.v1.GetResponse\x12@\n\x07Highest\x12\x16.google.protobuf.Empty\x1a\x1d.spacemesh.v1.HighestResponseB4Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.activation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_ACTIVATIONSERVICE']._serialized_start=114
  _globals['_ACTIVATIONSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
