# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spacemesh.v1 import activation_types_pb2 as spacemesh_dot_v1_dot_activation__types__pb2


class ActivationServiceStub(object):
    """Exposes services to query activation transactions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/spacemesh.v1.ActivationService/Get',
                request_serializer=spacemesh_dot_v1_dot_activation__types__pb2.GetRequest.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_activation__types__pb2.GetResponse.FromString,
                )
        self.Highest = channel.unary_unary(
                '/spacemesh.v1.ActivationService/Highest',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_activation__types__pb2.HighestResponse.FromString,
                )


class ActivationServiceServicer(object):
    """Exposes services to query activation transactions
    """

    def Get(self, request, context):
        """Get a single activation transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Highest(self, request, context):
        """Highest returns the atx id with the highest tick count.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=spacemesh_dot_v1_dot_activation__types__pb2.GetRequest.FromString,
                    response_serializer=spacemesh_dot_v1_dot_activation__types__pb2.GetResponse.SerializeToString,
            ),
            'Highest': grpc.unary_unary_rpc_method_handler(
                    servicer.Highest,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=spacemesh_dot_v1_dot_activation__types__pb2.HighestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spacemesh.v1.ActivationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActivationService(object):
    """Exposes services to query activation transactions
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spacemesh.v1.ActivationService/Get',
            spacemesh_dot_v1_dot_activation__types__pb2.GetRequest.SerializeToString,
            spacemesh_dot_v1_dot_activation__types__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Highest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spacemesh.v1.ActivationService/Highest',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            spacemesh_dot_v1_dot_activation__types__pb2.HighestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
