# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/admin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacemesh.v1 import admin_types_pb2 as spacemesh_dot_v1_dot_admin__types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18spacemesh/v1/admin.proto\x12\x0cspacemesh.v1\x1a\x1espacemesh/v1/admin_types.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc1\x02\n\x0c\x41\x64minService\x12\x63\n\x10\x43heckpointStream\x12%.spacemesh.v1.CheckpointStreamRequest\x1a&.spacemesh.v1.CheckpointStreamResponse0\x01\x12?\n\x07Recover\x12\x1c.spacemesh.v1.RecoverRequest\x1a\x16.google.protobuf.Empty\x12G\n\x0c\x45ventsStream\x12 .spacemesh.v1.EventStreamRequest\x1a\x13.spacemesh.v1.Event0\x01\x12\x42\n\x0ePeerInfoStream\x12\x16.google.protobuf.Empty\x1a\x16.spacemesh.v1.PeerInfo0\x01\x42\x34Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.admin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_ADMINSERVICE']._serialized_start=104
  _globals['_ADMINSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
