# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/debug.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacemesh.v1 import debug_types_pb2 as spacemesh_dot_v1_dot_debug__types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18spacemesh/v1/debug.proto\x12\x0cspacemesh.v1\x1a\x1espacemesh/v1/debug_types.proto\x1a\x1bgoogle/protobuf/empty.proto2\xb6\x02\n\x0c\x44\x65\x62ugService\x12H\n\x0bNetworkInfo\x12\x16.google.protobuf.Empty\x1a!.spacemesh.v1.NetworkInfoResponse\x12I\n\x08\x41\x63\x63ounts\x12\x1d.spacemesh.v1.AccountsRequest\x1a\x1e.spacemesh.v1.AccountsResponse\x12L\n\tActiveSet\x12\x1e.spacemesh.v1.ActiveSetRequest\x1a\x1f.spacemesh.v1.ActiveSetResponse\x12\x43\n\x0fProposalsStream\x12\x16.google.protobuf.Empty\x1a\x16.spacemesh.v1.Proposal0\x01\x42\x34Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.debug_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_DEBUGSERVICE']._serialized_start=104
  _globals['_DEBUGSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
