# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spacemesh.v1 import debug_types_pb2 as spacemesh_dot_v1_dot_debug__types__pb2


class DebugServiceStub(object):
    """DebugService exposes methods used for mostly debugging and tests
    NOTE: The endpoints in this service are experimental and subject to change without notice.
    They should not be used in production.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NetworkInfo = channel.unary_unary(
                '/spacemesh.v1.DebugService/NetworkInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.NetworkInfoResponse.FromString,
                )
        self.Accounts = channel.unary_unary(
                '/spacemesh.v1.DebugService/Accounts',
                request_serializer=spacemesh_dot_v1_dot_debug__types__pb2.AccountsRequest.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.AccountsResponse.FromString,
                )
        self.ActiveSet = channel.unary_unary(
                '/spacemesh.v1.DebugService/ActiveSet',
                request_serializer=spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetRequest.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetResponse.FromString,
                )
        self.ProposalsStream = channel.unary_stream(
                '/spacemesh.v1.DebugService/ProposalsStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.Proposal.FromString,
                )


class DebugServiceServicer(object):
    """DebugService exposes methods used for mostly debugging and tests
    NOTE: The endpoints in this service are experimental and subject to change without notice.
    They should not be used in production.
    """

    def NetworkInfo(self, request, context):
        """NetworkInfo returns p2p network information. Mostly required for integration with deployment 
        and testing tooling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accounts(self, request, context):
        """Accounts returns data for all the accounts currently in the node's current global state.
        This includes each account's address, nonce and balance but excludes projection of account state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveSet(self, request, context):
        """ActiveSet returns the active set used by hare in a given epoch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposalsStream(self, request, context):
        """ProposalsStream streams all proposals that are confirmed by hare.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DebugServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NetworkInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=spacemesh_dot_v1_dot_debug__types__pb2.NetworkInfoResponse.SerializeToString,
            ),
            'Accounts': grpc.unary_unary_rpc_method_handler(
                    servicer.Accounts,
                    request_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.AccountsRequest.FromString,
                    response_serializer=spacemesh_dot_v1_dot_debug__types__pb2.AccountsResponse.SerializeToString,
            ),
            'ActiveSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveSet,
                    request_deserializer=spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetRequest.FromString,
                    response_serializer=spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetResponse.SerializeToString,
            ),
            'ProposalsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ProposalsStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=spacemesh_dot_v1_dot_debug__types__pb2.Proposal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spacemesh.v1.DebugService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DebugService(object):
    """DebugService exposes methods used for mostly debugging and tests
    NOTE: The endpoints in this service are experimental and subject to change without notice.
    They should not be used in production.
    """

    @staticmethod
    def NetworkInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spacemesh.v1.DebugService/NetworkInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            spacemesh_dot_v1_dot_debug__types__pb2.NetworkInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Accounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spacemesh.v1.DebugService/Accounts',
            spacemesh_dot_v1_dot_debug__types__pb2.AccountsRequest.SerializeToString,
            spacemesh_dot_v1_dot_debug__types__pb2.AccountsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActiveSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spacemesh.v1.DebugService/ActiveSet',
            spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetRequest.SerializeToString,
            spacemesh_dot_v1_dot_debug__types__pb2.ActiveSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProposalsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/spacemesh.v1.DebugService/ProposalsStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            spacemesh_dot_v1_dot_debug__types__pb2.Proposal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
