# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/debug_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spacemesh.v1 import global_state_types_pb2 as spacemesh_dot_v1_dot_global__state__types__pb2
from spacemesh.v1 import types_pb2 as spacemesh_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espacemesh/v1/debug_types.proto\x12\x0cspacemesh.v1\x1a%spacemesh/v1/global_state_types.proto\x1a\x18spacemesh/v1/types.proto\" \n\x0f\x41\x63\x63ountsRequest\x12\r\n\x05layer\x18\x01 \x01(\r\"B\n\x10\x41\x63\x63ountsResponse\x12.\n\x0f\x61\x63\x63ount_wrapper\x18\x01 \x03(\x0b\x32\x15.spacemesh.v1.Account\"!\n\x13NetworkInfoResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1b\n\tEpochData\x12\x0e\n\x06\x62\x65\x61\x63on\x18\x01 \x01(\x0c\"+\n\x0b\x45ligibility\x12\t\n\x01j\x18\x01 \x01(\r\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"!\n\x10\x41\x63tiveSetRequest\x12\r\n\x05\x65poch\x18\x01 \x01(\r\"<\n\x11\x41\x63tiveSetResponse\x12\'\n\x03ids\x18\x01 \x03(\x0b\x32\x1a.spacemesh.v1.ActivationId\"\xf6\x02\n\x08Proposal\x12\n\n\x02id\x18\x01 \x01(\x0c\x12(\n\x05\x65poch\x18\x02 \x01(\x0b\x32\x19.spacemesh.v1.EpochNumber\x12(\n\x05layer\x18\x03 \x01(\x0b\x32\x19.spacemesh.v1.LayerNumber\x12(\n\x07smesher\x18\x04 \x01(\x0b\x32\x17.spacemesh.v1.SmesherId\x12\x13\n\treference\x18\x05 \x01(\x0cH\x00\x12\'\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x17.spacemesh.v1.EpochDataH\x00\x12\x0e\n\x06\x62\x61llot\x18\x07 \x01(\x0c\x12\x30\n\religibilities\x18\x08 \x03(\x0b\x32\x19.spacemesh.v1.Eligibility\x12-\n\x06status\x18\t \x01(\x0e\x32\x1d.spacemesh.v1.Proposal.Status\"#\n\x06Status\x12\x0b\n\x07\x43reated\x10\x00\x12\x0c\n\x08Included\x10\x01\x42\x0c\n\nepoch_dataB4Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.debug_types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_ACCOUNTSREQUEST']._serialized_start=113
  _globals['_ACCOUNTSREQUEST']._serialized_end=145
  _globals['_ACCOUNTSRESPONSE']._serialized_start=147
  _globals['_ACCOUNTSRESPONSE']._serialized_end=213
  _globals['_NETWORKINFORESPONSE']._serialized_start=215
  _globals['_NETWORKINFORESPONSE']._serialized_end=248
  _globals['_EPOCHDATA']._serialized_start=250
  _globals['_EPOCHDATA']._serialized_end=277
  _globals['_ELIGIBILITY']._serialized_start=279
  _globals['_ELIGIBILITY']._serialized_end=322
  _globals['_ACTIVESETREQUEST']._serialized_start=324
  _globals['_ACTIVESETREQUEST']._serialized_end=357
  _globals['_ACTIVESETRESPONSE']._serialized_start=359
  _globals['_ACTIVESETRESPONSE']._serialized_end=419
  _globals['_PROPOSAL']._serialized_start=422
  _globals['_PROPOSAL']._serialized_end=796
  _globals['_PROPOSAL_STATUS']._serialized_start=747
  _globals['_PROPOSAL_STATUS']._serialized_end=782
# @@protoc_insertion_point(module_scope)
