# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacemesh/v1/node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spacemesh.v1 import node_types_pb2 as spacemesh_dot_v1_dot_node__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17spacemesh/v1/node.proto\x12\x0cspacemesh.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dspacemesh/v1/node_types.proto2\x84\x04\n\x0bNodeService\x12=\n\x04\x45\x63ho\x12\x19.spacemesh.v1.EchoRequest\x1a\x1a.spacemesh.v1.EchoResponse\x12@\n\x07Version\x12\x16.google.protobuf.Empty\x1a\x1d.spacemesh.v1.VersionResponse\x12<\n\x05\x42uild\x12\x16.google.protobuf.Empty\x1a\x1b.spacemesh.v1.BuildResponse\x12\x43\n\x06Status\x12\x1b.spacemesh.v1.StatusRequest\x1a\x1c.spacemesh.v1.StatusResponse\x12\x42\n\x08NodeInfo\x12\x16.google.protobuf.Empty\x1a\x1e.spacemesh.v1.NodeInfoResponse\x12W\n\x0cStatusStream\x12!.spacemesh.v1.StatusStreamRequest\x1a\".spacemesh.v1.StatusStreamResponse0\x01\x12T\n\x0b\x45rrorStream\x12 .spacemesh.v1.ErrorStreamRequest\x1a!.spacemesh.v1.ErrorStreamResponse0\x01\x42\x34Z2github.com/spacemeshos/api/release/go/spacemesh/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacemesh.v1.node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/spacemeshos/api/release/go/spacemesh/v1'
  _globals['_NODESERVICE']._serialized_start=102
  _globals['_NODESERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
